spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 일반적인 서비스 라우트
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
        # Actuator 라우트를 먼저 정의 (더 구체적인 패턴)
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}

        - id: second-service
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - CustomFilter
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Global Filter
                preLogger: true
                postLogger: true
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true


server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges
